on:
  push:
    branches:
      - master
      - staging

jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      TARGET_ENVIRONMENT: ${{ steps.determine-target-environment.outputs.CLIENT_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - id: determine-target-environment
        run: echo "::set-output name=TARGET_ENVIRONMENT::${{ env.GITHUB_REF_NAME == 'master' && 'production' || 'staging' }}"
  check-environment:
    needs: [params]
    runs-on: ubuntu-latest
    environment: ${{ needs.params.outputs.TARGET_ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v3
      - run: echo $GITHUB_REF_NAME
      - run: echo ${{ needs.params.outputs.TARGET_ENVIRONMENT }}
      - run: echo $SSH_HOST
