on:
  push:
    branches:
      - master
      - staging

env:
  TEST_VARIABLE: "kek"

jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      TARGET_ENVIRONMENT: ${{ steps.determine-target-environment.outputs.TARGET_ENVIRONMENT }}
    steps:
      - run: echo $GITHUB_REF
      - run: echo "$GITHUB_REF_NAME"
      - run: echo "${{ toJSON(env) }}"
      - run: echo "${{ toJSON(github) }}"
      - run: env
      - id: determine-target-environment
        run: echo "::set-output name=TARGET_ENVIRONMENT::${{ github.ref_name == 'master' && 'production' || 'staging' }}"
  check-environment:
    needs: [params]
    runs-on: ubuntu-latest
    # environment: ${{ needs.params.outputs.TARGET_ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v3
      - run: echo $GITHUB_REF_NAME
      - run: echo ${{ needs.params.outputs.TARGET_ENVIRONMENT }}
      - run: echo $SSH_HOST
      - run: echo $TEST_VARIABLE
      - run: echo "${{ env.SSH_HOST }}"
      - run: echo "${{ secrets.SSH_HOST }}"
