on:
  pull_request_target:
    types:
      - closed
  push:
    branches:
      - master

jobs:
  always:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/print-info
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
