on:
  pull_request_target:
    types:
      - closed
  push:
    branches:
      - master

env:
  SOME_VERSION: 1.0

jobs:
  export-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/export-env
  use-exported-env:
    runs-on: ubuntu-latest
    needs: [export-env]
    steps:
      - run: echo SOME_VERSION ${{ steps.export-env.outputs.SOME_VERSION }}
  composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/print-info
  reusable-workflow:
    uses: ./.github/workflows/print-info.yml

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
