on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/print-info
  reusable-workflow:
    uses: ./.github/workflows/print-info.yml
