on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  always:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/print-info
