on: workflow_call

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event_name }}
      - if: ${{ github.event_name == 'pull_request' }}
        run: echo pull_request
      - if: ${{ github.event_name == 'push' }}
        run: echo push
