on: workflow_dispatch

jobs:
  variables:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - env:
          ALL_VARIABLES: ${{ toJson(vars) }}
          ALL_SECRETS: ${{ toJson(secrets) }}
        run: |
          echo "$ALL_VARIABLES" > "variables"
          echo "$ALL_SECRETS" > "secrets"
      - uses: mxschmitt/action-tmate@v3
