on: [push]

jobs:
  variables:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - env:
          VARIABLES: ${{ toJson(vars) }}
          SECRETS: ${{ toJson(secrets) }}
        run: |
          echo "$VARIABLES" > "variables"
          echo "$SECRETS" > "secrets"
      - uses: mxschmitt/action-tmate@v3
